
export const font = {
  MerriweatherSansBold: "MerriweatherSans-Bold",
  MerriweatherSansBoldItalic: "MerriweatherSans-BoldItalic",
  MerriweatherSansExtraBold: "MerriweatherSans-ExtraBold",
  MerriweatherSansExtraBoldItalic: "MerriweatherSans-ExtraBoldItalic",
  MerriweatherSansItalic: "MerriweatherSans-Italic",
  MerriweatherSansLight: "MerriweatherSans-Light",
  MerriweatherSansLightItalic: "MerriweatherSans-LightItalic",
  MerriweatherSansRegular: "MerriweatherSans-Regular",
  MontserratBlack: "Montserrat-Black",
  MontserratBlackItalic: "Montserrat-BlackItalic",
  MontserratBold: "Montserrat-Bold",
  MontserratBoldItalic: "Montserrat-BoldItalic",
  MontserratExtraBold: "Montserrat-ExtraBold",
  MontserratExtraBoldItalic: "Montserrat-ExtraBoldItalic",
  MontserratExtraLight: "Montserrat-ExtraLight",
  MontserratLight: "Montserrat-Light",
  MontserratMedium: "Montserrat-Medium",
  MontserratRegular: "Montserrat-Regular",
  MontserratSemiBold: "Montserrat-SemiBold",
  MontserratThin: "Montserrat-Thin",
  QuicksandVariableFont: "Quicksand-VariableFont:wght",
  SulphurPointBold: "SulphurPoint-Bold",
  SulphurPointLight: "SulphurPoint-Light",
  SulphurPointRegular: "SulphurPoint-Regular",
  UbuntuBold: "Ubuntu-Bold",
  UbuntuLight: "Ubuntu-Light",
  UbuntuMedium: "Ubuntu-Medium",
  UbuntuRegular: "Ubuntu-Regular"
}